services:
  redis:
    image: "redis"
    volumes:
      - data:/data/redisDB
  natours:
    build:
      context: ./Natours
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - logs:/app/natours/logs
      - ./natours:/app/natours
      - /app/natours/node_modules
    env_file:
      - ./Natours/config.env
  rediscache:
    build: ./redisCache
    ports:
      - "3001:3000"
    volumes:
      - logs2:/app/redisCache/logs
      - ./redisCache:/app/redisCache
      - /app/redisCache/node_modules
    depends_on:
      - redis
volumes:
  data:
  logs:
  logs2:
